package BankApp;


/**
* BankApp/BankInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Bank.idl
* Wednesday, 29 September, 2021 1:28:13 PM IST
*/

public interface BankInterface extends BankInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface BankInterface
