package BankApp;


/**
* BankApp/BankInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Bank.idl
* Wednesday, 29 September, 2021 1:28:13 PM IST
*/

abstract public class BankInterfaceHelper
{
  private static String  _id = "IDL:BankApp/BankInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, BankApp.BankInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static BankApp.BankInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (BankApp.BankInterfaceHelper.id (), "BankInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static BankApp.BankInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_BankInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, BankApp.BankInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static BankApp.BankInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof BankApp.BankInterface)
      return (BankApp.BankInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      BankApp._BankInterfaceStub stub = new BankApp._BankInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static BankApp.BankInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof BankApp.BankInterface)
      return (BankApp.BankInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      BankApp._BankInterfaceStub stub = new BankApp._BankInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
