package BankApp;


/**
* BankApp/BankInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Bank.idl
* Wednesday, 29 September, 2021 1:28:13 PM IST
*/

public interface BankInterfaceOperations 
{
  String getFixedDeposit (double x, double y);
  String getTotalAmount (double x, double y);
  void shutdown ();
} // interface BankInterfaceOperations
